### PR TITLE
Support erb in config file && allow silent branch-failure

### PR DESCRIPTION
**Pull request by petehamilton**
Allows injection of API key from environment using

```
<%= ENV['GEMNASIUM_API_KEY'] %>
```

If you want the config file versioned.

Also allows you to prevent an error-return if the current branch is not the specified gemnasium one.

### CODE REVIEW

**Comment by gonzoyumo** [comment]
Thanks for providing this. Can you please add some tests too?

You may also avoid bumping the version, we'll do it when releasing the gem and updating the changelog accordingly.
And why bumping to 2.0.2? There is no 2.0.1 release. Please revert this.

**Comment by petehamilton** [comment]
Sure, apologies for version bump, wasn't really thinking. Will update with tests shortly.

**Comment by gonzoyumo** [comment]
Getting close :) Can you please update the gemnasium_spec.rb too ? to ensure command behavior on a non tracked branch with the --ignore-branch option

**Comment by fcat** [comment]
The two features have in implemented in v3.1.0.

**Pull request closed without merging**
